export enum UserRole {
  ADMIN = 'ADMIN',
  RESEARCHER = 'RESEARCHER',
  FARMER = 'FARMER',
  FISHERMAN = 'FISHERMAN',
  PROCESSOR = 'PROCESSOR',
  TRADER = 'TRADER',
  RETAILER = 'RETAILER',
  CONSUMER = 'CONSUMER',
  PENDING_UPGRADE = 'PENDING_UPGRADE',
}